public enum GP_TBM_ParticipantResult
{
	MATCH_RESULT_UNINITIALIZED = -1,
	MATCH_RESULT_WIN,
	MATCH_RESULT_LOSS,
	MATCH_RESULT_TIE,
	MATCH_RESULT_NONE,
	MATCH_RESULT_DISCONNECT,
	MATCH_RESULT_DISAGREED
}
